version: '3.9'
services:
  ppg-app:
    container_name: ppg-app
    image: jeanp0/ppg-app:1.0.1
    build:
      context: .
      dockerfile: ./Dockerfile2
    ports:
      - 3000:3000
    restart: on-failure
