@base = http://localhost:3000/ppg-api/v1
@json = application/json
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NmE1ZjljMC1kYzAyLTQ0MTItYTA5ZC1jMGY0NTFmOGZiMjMiLCJpYXQiOjE2NTIxMjgxMTcsImV4cCI6MTY1MjE0OTcxN30.LphX2_tScU2fzclVvQvCP8p6Y_cm2UWd6xZosOM9wr0

### LOGIN
POST {{base}}/auth/login
Content-Type: {{json}}

{
  "email": "jeanpier@gmail.com",
  "password": "123456"
}

### GET TECHNOLOGIES
GET {{base}}/technologies
Authorization: Bearer {{jwt}}


### GET TECHNOLOGY BY ID
GET {{base}}/technologies/6d5158c9-1e89-47c9-8809-1dd7a9d65da8
Authorization: Bearer {{jwt}}

### GENERATE PROFILE

POST {{base}}/professional-profiles
Authorization: Bearer {{jwt}}
Content-Type: {{json}}

{
  "jobTitle": "Java Developer",
  "location": "Quito"
}
