export const frameworks = {
  'Entity Framework': ['entity framework', 'entityframework'],
  'Microsoft dotNET': ['dotnet', 'asp.net', '.net', 'microsoft .net'],
  'Ruby on Rails': ['ruby on rails', 'ruby'],
  'Spring Boot': ['spring boot', 'spring'],
  Angular: ['angular'],
  AngularJS: ['angularjs'],
  Blade: ['blade'],
  Django: ['django'],
  EmberJS: ['emberjs', 'ember', 'ember.js'],
  ExpressJS: ['expressjs', 'express.js'],
  FastAPI: ['fastapi'],
  FastifyJS: ['fastifyjs', 'fastify.js'],
  Flask: ['flask'],
  Flutter: ['flutter'],
  Gatsby: ['gatsby', 'gatsbyjs', 'gatsby.js'],
  Ionic: ['ionic'],
  Laravel: ['laravel'],
  LoopBack: ['loopback', 'loopback.js'],
  Lumel: ['lumen'],
  MeteorJS: ['meteorjs', 'meteor.js'],
  NestJS: ['nestjs', 'nest.js'],
  NextJS: ['nextjs', 'next.js'],
  NuxtJS: ['nuxtjs', 'nuxt.js'],
  Quarkus: ['quarkus', 'quarkus.io', 'quarkusio'],
  ReactJS: ['reactjs', 'react.js', 'react'],
  'React Native': ['react native', 'reactnative'],
  Svelte: ['svelte', 'sveltejs', 'svelte.js'],
  Symfony: ['symfony'],
  VueJS: ['vuejs', 'vue.js', 'vue', 'quasar'],
  Xamarin: ['xamarin'],
};
