export const languages = {
  'Node.js': ['nodejs', 'node.js', 'node'],
  JavaScript: ['javascript'],
  TypeScript: ['typescript'],
  'C#': ['csharp', 'c#'],
  'C++': ['cplusplus', 'c++'],
  Go: ['go', 'golang'],
  GrapQl: ['graphql'],
  Ruby: ['ruby'],
  C: ['language c', 'lenguaje c'],
  R: ['language r', 'lenguaje r'],
  Pascal: ['pascal'],
  Fortran: ['fortran'],
  Perl: ['perl'],
  HTML: ['html', 'html5'],
  PHP: ['php'],
  Python: ['python'],
  Java: ['java'],
  Kotlin: ['kotlin'],
  'Objective-C': ['objetive c', 'objetive-c'],
  Swift: ['swift'],
  Matlab: ['matlab'],
  SQL: ['sql'],
  CSS: ['css', 'css3'],
  SASS: ['sass'],
  XML: ['xml'],
  JSON: ['json'],
};
