export const languages = {
  NODEJS: ['nodejs', 'node.js', 'node'],
  JAVASCRIPT: ['javascript'],
  TYPESCRIPT: ['typescript'],
  CSHARP: ['csharp', 'c#'],
  CPLUSPLUS: ['cplusplus', 'c++'],
  GO: ['go', 'golang'],
  GRAPHQL: ['graphql'],
  C: ['c'],
  R: ['r'],
  PASCAL: ['pascal'],
  FORTRAN: ['fortran'],
  RUBY: ['ruby'],
  PERL: ['perl'],
  HTML: ['html', 'html5'],
  PHP: ['php'],
  PYTHON: ['python'],
  JAVA: ['java'],
  KOTLIN: ['kotlin'],
  OBJETIVE_C: ['objetivec', 'objetive-c'],
  SWIFT: ['swift'],
  MATLAB: ['matlab'],
  SQL: ['sql'],
  CSS: ['css', 'css3'],
  SASS: ['sass'],
  XML: ['xml'],
  JSON: ['json'],
  ruby: ['ruby'],
};
